// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKFR2-2hGt23_htRcb4zwI5mAr3FAXs5Q',
    appId: '1:338603757091:android:8343b2a3b04fb48ad16b96',
    messagingSenderId: '338603757091',
    projectId: 'lifecareplus-e76e9',
    storageBucket: 'lifecareplus-e76e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuD_FXzRkkDvmnquSC6pDfZzngF_IE4P0',
    appId: '1:338603757091:ios:b68820aae9ba92c5d16b96',
    messagingSenderId: '338603757091',
    projectId: 'lifecareplus-e76e9',
    storageBucket: 'lifecareplus-e76e9.firebasestorage.app',
    androidClientId: '338603757091-80nekvun6von51uukpu4roc88ndrdc1q.apps.googleusercontent.com',
    iosClientId: '338603757091-tfnrtumci0fbetgdjd8pn5kghvu9qed6.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifecareplus',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtPIxnyuT8BkrG5iBYz72Ugx-Wu7knWi4',
    appId: '1:338603757091:web:003e029dd40fd702d16b96',
    messagingSenderId: '338603757091',
    projectId: 'lifecareplus-e76e9',
    authDomain: 'lifecareplus-e76e9.firebaseapp.com',
    storageBucket: 'lifecareplus-e76e9.firebasestorage.app',
    measurementId: 'G-X7R5FGYM4R',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuD_FXzRkkDvmnquSC6pDfZzngF_IE4P0',
    appId: '1:338603757091:ios:b68820aae9ba92c5d16b96',
    messagingSenderId: '338603757091',
    projectId: 'lifecareplus-e76e9',
    storageBucket: 'lifecareplus-e76e9.firebasestorage.app',
    androidClientId: '338603757091-80nekvun6von51uukpu4roc88ndrdc1q.apps.googleusercontent.com',
    iosClientId: '338603757091-tfnrtumci0fbetgdjd8pn5kghvu9qed6.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifecareplus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtPIxnyuT8BkrG5iBYz72Ugx-Wu7knWi4',
    appId: '1:338603757091:web:66be468c8353fdd1d16b96',
    messagingSenderId: '338603757091',
    projectId: 'lifecareplus-e76e9',
    authDomain: 'lifecareplus-e76e9.firebaseapp.com',
    storageBucket: 'lifecareplus-e76e9.firebasestorage.app',
    measurementId: 'G-0NRMZ0CNDQ',
  );

}